title                    : "Your Name - AIGC & Time Series Researcher"
description              : "AI researcher focusing on diffusion models, time series forecasting, and AIGC applications"
repository               : "your_github_username/your_github_username.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # 可填写你自己的 GA ID

# SEO Related（可选）
google_site_verification :  
bing_site_verification   :  
baidu_site_verification  :  

author:
  name             : "Your Name"
  avatar           : "images/android-chrome-512x512.png"  # 可替换成你的照片路径
  bio              : "M.Sc in Electronic Information, AIGC Algorithm Engineer, Incoming Ph.D. Applicant"
  location         : "Beijing, China"
  employer         : "Zseads Technology, Alibaba, China Telecom (TeleAI)"
  googlescholar    : "https://scholar.google.com/citations?user=YOUR_ID"
  email            : "your_email@example.com"
  github           : "your_github_username"
  linkedin         : "your_linkedin_username"
  orcid            : "https://orcid.org/xxxx-xxxx-xxxx-xxxx"
  dblp             : "https://dblp.org/pid/xx/xxxx.html"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
